In [1]:
import pandas as pd

In [8]:
base_graph = pd.read_csv('../results/link_centrality_measures.csv')
base_graph = base_graph[base_graph['Edge Betweenness'] > 0]
base_graph = base_graph.sort_values(by='Edge Betweenness', ascending=False).reset_index(drop=True)
base_graph['Original Rank'] = base_graph.index + 1
print(base_graph)

                                                 Metros  Edge Betweenness  \
0     ('Los Angeles-Long Beach-Anaheim, CA Metro Are...          0.078958
1     ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.078192
2     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.071379
3     ('Seattle-Tacoma-Bellevue, WA Metro Area', 'Lo...          0.059718
4     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.055682
5     ('Philadelphia-Camden-Wilmington, PA-NJ-DE-MD ...          0.052499
6     ('Atlanta-Sandy Springs-Roswell, GA Metro Area...          0.051393
7     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.045599
8     ('Washington-Arlington-Alexandria, DC-VA-MD-WV...          0.045273
9     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.043262
10    ('Miami-Fort Lauderdale-West Palm Beach, FL Me...          0.043148
11    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.040751
12    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.037255
13    ('Minneapolis-St. Paul-Bloomington, MN-WI Metr...          0.033505
14    ('Los Angeles-Long Beach-Anaheim, CA Metro Are...          0.032666
15    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.029669
16    ('Indianapolis-Carmel-Anderson, IN Metro Area'...          0.029276
17    ('Los Angeles-Long Beach-Anaheim, CA Metro Are...          0.028750
18    ('Boston-Cambridge-Newton, MA-NH Metro Area', ...          0.027605
19    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.027471
20    ('Phoenix-Mesa-Scottsdale, AZ Metro Area', 'Lo...          0.027272
21    ('Dallas-Fort Worth-Arlington, TX Metro Area',...          0.027065
22    ('Detroit-Warren-Dearborn, MI Metro Area', 'Ch...          0.027059
23    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.026885
24    ('Atlanta-Sandy Springs-Roswell, GA Metro Area...          0.025707
25    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.025627
26    ('St. Louis, MO-IL Metro Area', 'Chicago-Naper...          0.025507
27    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.025420
28    ('Atlanta-Sandy Springs-Roswell, GA Metro Area...          0.024867
29    ('Los Angeles-Long Beach-Anaheim, CA Metro Are...          0.024748
...                                                 ...               ...
1260  ('Staunton-Waynesboro, VA Metro Area', 'Charlo...          0.000007
1261  ('Staunton-Waynesboro, VA Metro Area', 'Harris...          0.000007
1262  ('Cape Coral-Fort Myers, FL Metro Area', 'Napl...          0.000007
1263  ('Fayetteville, NC Metro Area', 'Watertown-For...          0.000007
1264  ('Bridgeport-Stamford-Norwalk, CT Metro Area',...          0.000007
1265  ('Santa Cruz-Watsonville, CA Metro Area', 'Sal...          0.000007
1266  ('Fayetteville, NC Metro Area', 'Wilmington, N...          0.000007
1267  ('Fresno, CA Metro Area', 'Bakersfield, CA Met...          0.000007
1268  ('Bloomsburg-Berwick, PA Metro Area', 'Scranto...          0.000007
1269  ('Bloomington, IL Metro Area', 'Peoria, IL Met...          0.000007
1270  ('Manhattan, KS Metro Area', 'Topeka, KS Metro...          0.000007
1271  ('Altoona, PA Metro Area', 'State College, PA ...          0.000007
1272  ('Altoona, PA Metro Area', 'Johnstown, PA Metr...          0.000007
1273  ('Owensboro, KY Metro Area', 'Lexington-Fayett...          0.000007
1274  ('Yakima, WA Metro Area', 'Kennewick-Richland,...          0.000007
1275  ('San Germán, PR Metro Area', 'Mayagüez, PR Me...          0.000007
1276  ('McAllen-Edinburg-Mission, TX Metro Area', 'B...          0.000007
1277  ('Odessa, TX Metro Area', 'Midland, TX Metro A...          0.000007
1278  ('Columbia, MO Metro Area', 'Jefferson City, M...          0.000007
1279  ('Davenport-Moline-Rock Island, IA-IL Metro Ar...          0.000007
1280  ('Lebanon, PA Metro Area', 'Lancaster, PA Metr...          0.000007
1281  ('Durham-Chapel Hill, NC Metro Area', 'Greensb...          0.000007
1282  ('Hartford-West Hartford-East Hartford, CT Met...          0.000007
1283  ('Hilton Head Island-Bluffton-Beaufort, SC Met...          0.000007
1284  ('Elmira, NY Metro Area', 'Binghamton, NY Metr...          0.000007
1285  ('Evansville, IN-KY Metro Area', 'Owensboro, K...          0.000007
1286  ('Stockton-Lodi, CA Metro Area', 'Modesto, CA ...          0.000007
1287  ('Aguadilla-Isabela, PR Metro Area', 'Mayagüez...          0.000007
1288  ('Grand Forks, ND-MN Metro Area', 'Bismarck, N...          0.000007
1289  ('New Bern, NC Metro Area', 'Jacksonville, NC ...          0.000007

      Original Rank
0                 1
1                 2
2                 3
3                 4
4                 5
5                 6
6                 7
7                 8
8                 9
9                10
10               11
11               12
12               13
13               14
14               15
15               16
16               17
17               18
18               19
19               20
20               21
21               22
22               23
23               24
24               25
25               26
26               27
27               28
28               29
29               30
...             ...
1260           1261
1261           1262
1262           1263
1263           1264
1264           1265
1265           1266
1266           1267
1267           1268
1268           1269
1269           1270
1270           1271
1271           1272
1272           1273
1273           1274
1274           1275
1275           1276
1276           1277
1277           1278
1278           1279
1279           1280
1280           1281
1281           1282
1282           1283
1283           1284
1284           1285
1285           1286
1286           1287
1287           1288
1288           1289
1289           1290

[1290 rows x 3 columns]

In [10]:
weighted_graph = pd.read_csv('../results/weighted_income_edge_centrality.csv')
weighted_graph['Weighted Rank'] = weighted_graph.index + 1
print(weighted_graph)

                                                 Metros  Edge Betweenness  \
0     ('Los Angeles-Long Beach-Anaheim, CA Metro Are...          0.107561
1     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.091911
2     ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.084452
3     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.062975
4     ('Seattle-Tacoma-Bellevue, WA Metro Area', 'Lo...          0.059844
5     ('Atlanta-Sandy Springs-Roswell, GA Metro Area...          0.058359
6     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.054297
7     ('Philadelphia-Camden-Wilmington, PA-NJ-DE-MD ...          0.053598
8     ('Washington-Arlington-Alexandria, DC-VA-MD-WV...          0.053105
9     ('Miami-Fort Lauderdale-West Palm Beach, FL Me...          0.045679
10    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.042489
11    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.041270
12    ('Minneapolis-St. Paul-Bloomington, MN-WI Metr...          0.036622
13    ('Los Angeles-Long Beach-Anaheim, CA Metro Are...          0.032440
14    ('Phoenix-Mesa-Scottsdale, AZ Metro Area', 'Lo...          0.031361
15    ('Dallas-Fort Worth-Arlington, TX Metro Area',...          0.029962
16    ('Indianapolis-Carmel-Anderson, IN Metro Area'...          0.029376
17    ('Detroit-Warren-Dearborn, MI Metro Area', 'Ch...          0.029250
18    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.028570
19    ('Boston-Cambridge-Newton, MA-NH Metro Area', ...          0.027618
20    ('Dallas-Fort Worth-Arlington, TX Metro Area',...          0.027425
21    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.027411
22    ('San Francisco-Oakland-Hayward, CA Metro Area...          0.027278
23    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.026885
24    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.026719
25    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...          0.026606
26    ('Atlanta-Sandy Springs-Roswell, GA Metro Area...          0.026253
27    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...          0.026213
28    ('Houston-The Woodlands-Sugar Land, TX Metro A...          0.026100
29    ('St. Louis, MO-IL Metro Area', 'Chicago-Naper...          0.025434
...                                                 ...               ...
1178  ('Chambersburg-Waynesboro, PA Metro Area', 'Ha...          0.000007
1179  ('East Stroudsburg, PA Metro Area', 'Allentown...          0.000007
1180  ('Santa Cruz-Watsonville, CA Metro Area', 'Sal...          0.000007
1181  ('Elizabethtown-Fort Knox, KY Metro Area', 'Ki...          0.000007
1182  ('San Luis Obispo-Paso Robles-Arroyo Grande, C...          0.000007
1183  ('Gettysburg, PA Metro Area', 'Chambersburg-Wa...          0.000007
1184  ('Morristown, TN Metro Area', 'Kingsport-Brist...          0.000007
1185  ('Hilton Head Island-Bluffton-Beaufort, SC Met...          0.000007
1186  ('Jackson, MS Metro Area', 'Gulfport-Biloxi-Pa...          0.000007
1187  ('Bloomington, IL Metro Area', 'Peoria, IL Met...          0.000007
1188  ('Fayetteville, NC Metro Area', 'Crestview-For...          0.000007
1189  ('Blacksburg-Christiansburg-Radford, VA Metro ...          0.000007
1190  ('Salisbury, MD-DE Metro Area', 'Dover, DE Met...          0.000007
1191  ('Auburn-Opelika, AL Metro Area', 'Columbus, G...          0.000007
1192  ('Fayetteville, NC Metro Area', 'Clarksville, ...          0.000007
1193  ('Altoona, PA Metro Area', 'State College, PA ...          0.000007
1194  ('Altoona, PA Metro Area', 'Johnstown, PA Metr...          0.000007
1195  ('Sebastian-Vero Beach, FL Metro Area', 'Palm ...          0.000007
1196  ('Sebastian-Vero Beach, FL Metro Area', 'Port ...          0.000007
1197  ('Fayetteville, NC Metro Area', 'Killeen-Templ...          0.000007
1198  ('Hilton Head Island-Bluffton-Beaufort, SC Met...          0.000007
1199  ('The Villages, FL Metro Area', 'Ocala, FL Met...          0.000007
1200  ('Fresno, CA Metro Area', 'Bakersfield, CA Met...          0.000007
1201  ('Cedar Rapids, IA Metro Area', 'Dubuque, IA M...          0.000007
1202  ('Clarksville, TN-KY Metro Area', 'Fayettevill...          0.000007
1203  ('Fayetteville-Springdale-Rogers, AR-MO Metro ...          0.000007
1204  ('Anniston-Oxford-Jacksonville, AL Metro Area'...          0.000007
1205  ('Gainesville, FL Metro Area', 'Jacksonville, ...          0.000007
1206  ('Lebanon, PA Metro Area', 'Lancaster, PA Metr...          0.000007
1207  ('Monroe, MI Metro Area', 'Toledo, OH Metro Ar...          0.000007

      Weighted Rank
0                 1
1                 2
2                 3
3                 4
4                 5
5                 6
6                 7
7                 8
8                 9
9                10
10               11
11               12
12               13
13               14
14               15
15               16
16               17
17               18
18               19
19               20
20               21
21               22
22               23
23               24
24               25
25               26
26               27
27               28
28               29
29               30
...             ...
1178           1179
1179           1180
1180           1181
1181           1182
1182           1183
1183           1184
1184           1185
1185           1186
1186           1187
1187           1188
1188           1189
1189           1190
1190           1191
1191           1192
1192           1193
1193           1194
1194           1195
1195           1196
1196           1197
1197           1198
1198           1199
1199           1200
1200           1201
1201           1202
1202           1203
1203           1204
1204           1205
1205           1206
1206           1207
1207           1208

[1208 rows x 3 columns]

In [15]:
merged = pd.merge(base_graph,weighted_graph,on=['Metros'], how='inner')[['Metros','Original Rank', 'Weighted Rank']]
merged['Delta Rank'] = merged['Weighted Rank'] - merged['Original Rank'] 
print(merged)

                                                 Metros  Original Rank  \
0     ('Los Angeles-Long Beach-Anaheim, CA Metro Are...              1
1     ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...              2
2     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...              3
3     ('Seattle-Tacoma-Bellevue, WA Metro Area', 'Lo...              4
4     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...              5
5     ('Philadelphia-Camden-Wilmington, PA-NJ-DE-MD ...              6
6     ('Atlanta-Sandy Springs-Roswell, GA Metro Area...              7
7     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...              8
8     ('Washington-Arlington-Alexandria, DC-VA-MD-WV...              9
9     ('New York-Newark-Jersey City, NY-NJ-PA Metro ...             10
10    ('Miami-Fort Lauderdale-West Palm Beach, FL Me...             11
11    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...             12
12    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...             13
13    ('Minneapolis-St. Paul-Bloomington, MN-WI Metr...             14
14    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...             16
15    ('Indianapolis-Carmel-Anderson, IN Metro Area'...             17
16    ('Los Angeles-Long Beach-Anaheim, CA Metro Are...             18
17    ('Boston-Cambridge-Newton, MA-NH Metro Area', ...             19
18    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...             20
19    ('Phoenix-Mesa-Scottsdale, AZ Metro Area', 'Lo...             21
20    ('Dallas-Fort Worth-Arlington, TX Metro Area',...             22
21    ('Detroit-Warren-Dearborn, MI Metro Area', 'Ch...             23
22    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...             24
23    ('Atlanta-Sandy Springs-Roswell, GA Metro Area...             25
24    ('New York-Newark-Jersey City, NY-NJ-PA Metro ...             26
25    ('St. Louis, MO-IL Metro Area', 'Chicago-Naper...             27
26    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...             28
27    ('Atlanta-Sandy Springs-Roswell, GA Metro Area...             29
28    ('Los Angeles-Long Beach-Anaheim, CA Metro Are...             30
29    ('Chicago-Naperville-Elgin, IL-IN-WI Metro Are...             31
...                                                 ...            ...
1136  ('Jackson, MI Metro Area', 'Battle Creek, MI M...           1247
1137  ('Sebastian-Vero Beach, FL Metro Area', 'Port ...           1249
1138  ('Tyler, TX Metro Area', 'Longview, TX Metro A...           1250
1139  ('Sebastian-Vero Beach, FL Metro Area', 'Palm ...           1252
1140  ('Modesto, CA Metro Area', 'Merced, CA Metro A...           1253
1141  ('Shreveport-Bossier City, LA Metro Area', 'Mo...           1254
1142  ('Salisbury, MD-DE Metro Area', 'Dover, DE Met...           1255
1143  ('Lake Charles, LA Metro Area', 'Lafayette, LA...           1258
1144  ('Ocean City, NJ Metro Area', 'Atlantic City-H...           1259
1145  ('Grand Forks, ND-MN Metro Area', 'Fargo, ND-M...           1260
1146  ('Staunton-Waynesboro, VA Metro Area', 'Charlo...           1261
1147  ('Staunton-Waynesboro, VA Metro Area', 'Harris...           1262
1148  ('Cape Coral-Fort Myers, FL Metro Area', 'Napl...           1263
1149  ('Bridgeport-Stamford-Norwalk, CT Metro Area',...           1265
1150  ('Santa Cruz-Watsonville, CA Metro Area', 'Sal...           1266
1151  ('Fresno, CA Metro Area', 'Bakersfield, CA Met...           1268
1152  ('Bloomsburg-Berwick, PA Metro Area', 'Scranto...           1269
1153  ('Bloomington, IL Metro Area', 'Peoria, IL Met...           1270
1154  ('Altoona, PA Metro Area', 'State College, PA ...           1272
1155  ('Altoona, PA Metro Area', 'Johnstown, PA Metr...           1273
1156  ('Owensboro, KY Metro Area', 'Lexington-Fayett...           1274
1157  ('Odessa, TX Metro Area', 'Midland, TX Metro A...           1278
1158  ('Columbia, MO Metro Area', 'Jefferson City, M...           1279
1159  ('Davenport-Moline-Rock Island, IA-IL Metro Ar...           1280
1160  ('Lebanon, PA Metro Area', 'Lancaster, PA Metr...           1281
1161  ('Durham-Chapel Hill, NC Metro Area', 'Greensb...           1282
1162  ('Hilton Head Island-Bluffton-Beaufort, SC Met...           1284
1163  ('Elmira, NY Metro Area', 'Binghamton, NY Metr...           1285
1164  ('Evansville, IN-KY Metro Area', 'Owensboro, K...           1286
1165  ('Stockton-Lodi, CA Metro Area', 'Modesto, CA ...           1287

      Weighted Rank  Delta Rank
0                 1           0
1                 3           1
2                 4           1
3                 5           1
4                 2          -3
5                 8           2
6                 6          -1
7                 7          -1
8                 9           0
9                11           1
10               10          -1
11               22          10
12               12          -1
13               13          -1
14               19           3
15               17           0
16               14          -4
17               20           1
18               24           4
19               15          -6
20               21          -1
21               18          -5
22               28           4
23               27           2
24               37          11
25               30           3
26               25          -3
27               38           9
28               32           2
29               33           2
...             ...         ...
1136           1137        -110
1137           1197         -52
1138           1167         -83
1139           1196         -56
1140           1144        -109
1141           1178         -76
1142           1191         -64
1143           1119        -139
1144           1166         -93
1145           1123        -137
1146           1037        -224
1147           1122        -140
1148           1164         -99
1149            675        -590
1150           1181         -85
1151           1201         -67
1152           1165        -104
1153           1188         -82
1154           1194         -78
1155           1195         -78
1156           1107        -167
1157           1104        -174
1158           1142        -137
1159           1125        -155
1160           1207         -74
1161           1127        -155
1162           1186         -98
1163           1128        -157
1164           1131        -155
1165           1100        -187

[1166 rows x 4 columns]

In [16]:
merged.to_csv('../results/link_centrality_changes.csv', index=False)