In [12]:
# The codes for Hispanic origin are: 
# 01 = White alone, not Hispanic or Latino, 
# 02 = Other race, not Hispanic or Latino,
# 03 = Hispanic or Latino.

In [13]:
import networkx as nx
import pandas as pd
from functools import reduce

In [16]:
def load_data():
    non_cities = ['Outside Metro Area within U.S. or Puerto Rico', 'Africa', 'Asia', 'Central America', 'Caribbean', 'Europe', 'U.S. Island Areas', 'Northern America', 'Oceania and At Sea', 'South America']
    
    G_01 = nx.DiGraph()
    G_02 = nx.DiGraph()
    G_03 = nx.DiGraph()

    x = pd.ExcelFile('../data/metro-to-metro-by-hispanic-origin-2011-2015.xlsx')
    print(x.sheet_names)

    hispanic = 'Unnamed: 2'
    current = 'Unnamed: 3'
    previous = 'Unnamed: 16'
    
    count = 'Unnamed: 27'

    thresh = 0

    for state in x.sheet_names:
        df = x.parse(state)

        for index, row in df.iterrows():

            # skip first three rows: header rows
            if index < 3:
                continue
            # skip the last rows: footer rows
            if index >= 51533:
                break

            if int(row[count]) < thresh:
                continue

            # exclude non-cities
            if row[previous] in non_cities or row[current] in non_cities:
                continue
                
            # get hispanic origin code
            if row[hispanic] == '01':
                G_01.add_edge(row[previous], row[current], weight=int(row[count]))
            elif row[hispanic] == '02':
                G_02.add_edge(row[previous], row[current], weight=int(row[count]))
            elif row[hispanic] == '03':
                G_03.add_edge(row[previous], row[current], weight=int(row[count]))
                
    return [G_01, G_02, G_03]

In [17]:
hisp_graphs = load_data()
for g in hisp_graphs:
    print(str(len(g.nodes())) + " , " + str(len(g.edges())))

['Metro-to-Metro by Hispanic Orig']
388 , 21316
388 , 13607
388 , 9938

In [19]:
def pagerank(filename, graph):
    val_name = filename + '_value'
    rank_name = filename + '_rank'
    
    pr = nx.pagerank(graph, max_iter=1000)
    pr_df = pd.DataFrame.from_dict(pr, orient='index', columns=[val_name]).reset_index().rename(columns={'index':'metro'})
    pr_df = pr_df.sort_values(by=val_name, ascending=False).reset_index(drop=True)
    pr_df[rank_name] = pr_df.index + 1
    
    return pr_df

In [20]:
filenames = ['white_nonhisp', 'other_nonhisp', 'hisp']

pr_dfs = []
for f,g in zip(filenames, hisp_graphs):
    pr_dfs.append(pagerank(f,g))

pr_merged = reduce(lambda  left,right: pd.merge(left,right,on=['metro'], how='outer'), pr_dfs)
print(pr_merged)

                                                 metro  white_nonhisp_value  \
0    Washington-Arlington-Alexandria, DC-VA-MD-WV M...             0.022388
1     New York-Newark-Jersey City, NY-NJ-PA Metro Area             0.021902
2           Dallas-Fort Worth-Arlington, TX Metro Area             0.021891
3        Chicago-Naperville-Elgin, IL-IN-WI Metro Area             0.018698
4        Los Angeles-Long Beach-Anaheim, CA Metro Area             0.018083
5               Phoenix-Mesa-Scottsdale, AZ Metro Area             0.017331
6      Houston-The Woodlands-Sugar Land, TX Metro Area             0.016518
7         Atlanta-Sandy Springs-Roswell, GA Metro Area             0.016495
8                Denver-Aurora-Lakewood, CO Metro Area             0.015270
9               Seattle-Tacoma-Bellevue, WA Metro Area             0.014186
10   Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...             0.013511
11           Boston-Cambridge-Newton, MA-NH Metro Area             0.012360
12   Minneapolis-St. Paul-Bloomington, MN-WI Metro ...             0.011774
13      Tampa-St. Petersburg-Clearwater, FL Metro Area             0.011720
14   Miami-Fort Lauderdale-West Palm Beach, FL Metr...             0.011691
15                    Austin-Round Rock, TX Metro Area             0.010957
16        San Francisco-Oakland-Hayward, CA Metro Area             0.010202
17     Riverside-San Bernardino-Ontario, CA Metro Area             0.010115
18                   San Diego-Carlsbad, CA Metro Area             0.009913
19        Charlotte-Concord-Gastonia, NC-SC Metro Area             0.009883
20            Orlando-Kissimmee-Sanford, FL Metro Area             0.009776
21      Portland-Vancouver-Hillsboro, OR-WA Metro Area             0.009338
22   Virginia Beach-Norfolk-Newport News, VA-NC Met...             0.009141
23   Nashville-Davidson--Murfreesboro--Franklin, TN...             0.009138
24            Baltimore-Columbia-Towson, MD Metro Area             0.008428
25              Detroit-Warren-Dearborn, MI Metro Area             0.007779
26            San Antonio-New Braunfels, TX Metro Area             0.007644
27                       Kansas City, MO-KS Metro Area             0.007573
28                         St. Louis, MO-IL Metro Area             0.007514
29         Indianapolis-Carmel-Anderson, IN Metro Area             0.007192
..                                                 ...                  ...
358                                Lima, OH Metro Area             0.000656
359                         Rocky Mount, NC Metro Area             0.000647
360                   Janesville-Beloit, WI Metro Area             0.000644
361                              Sumter, SC Metro Area             0.000638
362                  Parkersburg-Vienna, WV Metro Area             0.000632
363                       Cumberland, MD-WV Metro Area             0.000629
364                         Great Falls, MT Metro Area             0.000614
365                        Texarkana, TX-AR Metro Area             0.000611
366                         Carson City, NV Metro Area             0.000597
367                              Elmira, NY Metro Area             0.000589
368                            Columbus, IN Metro Area             0.000582
369                           Pocatello, ID Metro Area             0.000575
370                            Victoria, TX Metro Area             0.000561
371                          Pine Bluff, AR Metro Area             0.000541
372                         Lewiston, ID-WA Metro Area             0.000540
373                           Owensboro, KY Metro Area             0.000540
374               Brownsville-Harlingen, TX Metro Area             0.000533
375                        Grand Island, NE Metro Area             0.000521
376                           El Centro, CA Metro Area             0.000504
377                              Kokomo, IN Metro Area             0.000504
378                          Farmington, NM Metro Area             0.000501
379                              Laredo, TX Metro Area             0.000485
380                               Ponce, PR Metro Area             0.000482
381                            Longview, WA Metro Area             0.000464
382                            Danville, IL Metro Area             0.000459
383                             Guayama, PR Metro Area             0.000414
384                   Aguadilla-Isabela, PR Metro Area             0.000395
385                             Arecibo, PR Metro Area             0.000390
386                            Mayagüez, PR Metro Area             0.000387
387                          San Germán, PR Metro Area             0.000387

     white_nonhisp_rank  other_nonhisp_value  other_nonhisp_rank  hisp_value  \
0                     1             0.029508                   3    0.017776
1                     2             0.032630                   2    0.030996
2                     3             0.028629                   4    0.027473
3                     4             0.021891                   7    0.019046
4                     5             0.027254                   5    0.033027
5                     6             0.012704                  14    0.019528
6                     7             0.025388                   6    0.029409
7                     8             0.037631                   1    0.013999
8                     9             0.007511                  29    0.010467
9                    10             0.015443                  10    0.012545
10                   11             0.015677                   9    0.012396
11                   12             0.010181                  19    0.008037
12                   13             0.011509                  16    0.006542
13                   14             0.007159                  31    0.012025
14                   15             0.013273                  12    0.024010
15                   16             0.009968                  20    0.016623
16                   17             0.015701                   8    0.010601
17                   18             0.014996                  11    0.029444
18                   19             0.009340                  22    0.012748
19                   20             0.013186                  13    0.007028
20                   21             0.009796                  21    0.018852
21                   22             0.006339                  34    0.005729
22                   23             0.011060                  17    0.008267
23                   24             0.005128                  42    0.005492
24                   25             0.012437                  15    0.005164
25                   26             0.008837                  23    0.004410
26                   27             0.007879                  27    0.023969
27                   28             0.006675                  33    0.005589
28                   29             0.007680                  28    0.003989
29                   30             0.006024                  36    0.004098
..                  ...                  ...                 ...         ...
358                 359             0.000555                 349    0.000468
359                 360             0.001276                 177    0.000538
360                 361             0.000507                 364    0.000534
361                 362             0.000930                 241    0.000468
362                 363             0.000435                 378    0.000405
363                 364             0.000671                 316    0.000484
364                 365             0.000901                 254    0.000845
365                 366             0.000920                 243    0.000523
366                 367             0.000509                 362    0.000618
367                 368             0.000678                 312    0.000462
368                 369             0.000499                 366    0.000622
369                 370             0.000540                 355    0.000478
370                 371             0.000473                 375    0.001062
371                 372             0.000973                 234    0.000471
372                 373             0.000493                 369    0.000476
373                 374             0.000615                 335    0.000414
374                 375             0.000477                 371    0.002269
375                 376             0.000469                 376    0.000667
376                 377             0.000586                 340    0.001871
377                 378             0.000511                 361    0.000399
378                 379             0.000518                 358    0.000612
379                 380             0.000413                 382    0.001821
380                 381             0.000403                 384    0.002624
381                 382             0.000432                 380    0.000429
382                 383             0.000567                 348    0.000434
383                 384             0.000407                 383    0.000746
384                 385             0.000396                 385    0.001771
385                 386             0.000387                 386    0.000963
386                 387             0.000387                 388    0.001385
387                 388             0.000387                 387    0.000702

     hisp_rank
0           11
1            2
2            5
3            9
4            1
5            8
6            4
7           13
8           20
9           15
10          16
11          23
12          27
13          17
14           6
15          12
16          18
17           3
18          14
19          25
20          10
21          33
22          22
23          36
24          40
25          45
26           7
27          35
28          52
29          49
..         ...
358        374
359        351
360        353
361        373
362        385
363        365
364        258
365        355
366        321
367        375
368        320
369        368
370        205
371        372
372        371
373        383
374         99
375        303
376        124
377        387
378        324
379        129
380         86
381        380
382        379
383        282
384        134
385        226
386        167
387        291

[388 rows x 7 columns]

In [21]:
pr_merged.to_csv('../results/hisp_pagerank.csv', index=False)